In [1]:
[None]*7

[None, None, None, None, None, None, None]

In [2]:
from sklearn.cluster import KMeans


In [10]:
import numpy as np

In [15]:
data = np.array([[4,8,12,18]])
data

array([[ 4,  8, 12, 18]])

In [16]:
kmeans = KMeans(n_clusters=2)
kmeans.fit_predict(data)

ValueError: n_samples=1 should be >= n_clusters=2.

In [17]:
data = np.array([4, 8, 12, 18]).reshape(-1, 1)  # Reshape to 2D array for KMeans

# Apply k-means clustering (k=2 for two routers/clusters)
kmeans = KMeans(n_clusters=2, random_state=0)
kmeans.fit_predict(data)

array([1, 1, 0, 0])

In [19]:
centroids = kmeans.cluster_centers_
centroids

array([[15.],
       [ 6.]])

In [1]:
a = 'abcccc'
set(a)

{'a', 'b', 'c'}

In [2]:
b = 'abdc'
zip_longest(a,b)

NameError: name 'zip_longest' is not defined

In [5]:
from itertools import zip_longest
len(set(zip_longest(a,b)))

5