In [208]:
import pandas as pd 
import numpy as np

In [209]:
df = pd.DataFrame({"A": [10,20,30,40,50], 
                   "B": [20, 30, 10, 40, 50], 
                   "C": [32, 234, 23, 23, 42523]})

In [210]:
df

A   B      C
0  10  20     32
1  20  30    234
2  30  10     23
3  40  40     23
4  50  50  42523

In [211]:
X = df.iloc[:,0:2].values
ones = np.ones([X.shape[0],1]) # constant
X = np.concatenate((ones,X),axis=1)
X

array([[ 1., 10., 20.],
       [ 1., 20., 30.],
       [ 1., 30., 10.],
       [ 1., 40., 40.],
       [ 1., 50., 50.]])

In [212]:
X.shape[0]

5

In [213]:
y = df.iloc[:,2:3].values
y

array([[   32],
       [  234],
       [   23],
       [   23],
       [42523]], dtype=int64)

In [214]:
beta = np.zeros([1,3])
beta

array([[0., 0., 0.]])

In [215]:
def cost_function(X,y,beta):
    n = X.shape[0]
    sum_squared = np.sum(np.power((X@beta.T - y),2))
    return sum_squared

In [216]:
cost_function(X,y,beta)

1808262367.0

In [217]:
def gradientDescent(X, y, beta, n, alpha):
    """
    using gradient descent to minimize cost function.
    
    Parameters
    ----------
    X : array_like
        explanatory variables
    y: array_like
        response variable
    beta: array_like
        a list of coefficient
    n: int
        number of iterations
    alpha: float
        learning rate
    
    Return
    ------
    beta: array_like
        updated coefficient
    cost: array_like
        cost history
    """
    cost = np.zeros(n) # initial costs are 0
    for i in range(n):
        beta = beta - (alpha/len(X)) * np.sum(X * (X @ beta.T - y), axis = 0) # iteratively update beta
        cost[i] = cost_function(X, y, beta) # update cost 
    return beta, cost

In [220]:
gradientDescent(X,y,beta,100000,0.0005)

(array([[-21383.38692163,    495.52660001,    502.85993335]]),
 array([9.61518757e+08, 9.57261798e+08, 9.57182815e+08, ...,
        5.93665235e+08, 5.93665235e+08, 5.93665235e+08]))

In [ ]:
def optim_iterative(X,y,beta,alpha,iter):
    n = X.shape[0]
    iter_cost = np.zeros(iter)
    
    for i in range(iter):
        iter_cost[i] = cost_function(X,y,beta)
        beta = (beta -  (alpha/iter)*(np.sum(X * ((X@beta.T - y)).reshape(5),axis=1)))
    return iter_cost,beta
        

In [158]:
optim_iterative(X,y,beta,0.01,10000)

(array([1.80826237e+09, 1.79014276e+09, 1.77240897e+09, ...,
        9.51620694e+08, 9.51620125e+08, 9.51619557e+08]),
 array([[-163.64438866],
        [ 198.21396625],
        [ 205.18235871]]))

In [90]:
beta.T -  np.sum(X.T * ((X@beta - y.reshape(len(y),1))).reshape(5),axis=1)

array([[2130781.09619519, 2133084.93041324]])

In [157]:
import statsmodels.formula.api as sm
result = sm.ols(formula="A ~ B + C", data=df).fit()
print(result.params)

Intercept    14.952480
B             0.401182
C             0.000352
dtype: float64
